#database/postgresql
spring.datasource.url=jdbc:postgresql://localhost:5433/auth_service
spring.datasource.username=auth_service_user
spring.datasource.password=AuthAdmin

#jpa/hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

#cache/redis
spring.data.redis.port=6379
spring.data.redis.host=localhost
spring.data.redis.database=0
spring.data.redis.username=
spring.data.redis.password=

#security
spring.security.user.name=user
spring.security.user.password=password